{{ $architecture := or .architecture "arm64" }}
{{ $suite := or .suite "trixie" }}
{{ $image := or .image (printf "iara-linux-%s" $suite) }}

architecture: {{ $architecture }}

actions:
  - action: recipe
    description: Steps
    recipe: steps/steps.yaml

  - action: image-partition
    description: Step 97, Partition the image
    imagename: {{ $image }}.img
    imagesize: 2GiB
    partitiontype: gpt
    partitions:
      - name: boot
        fs: ext4
        start: 1MiB
        end: 129MiB
      - name: root
        fs: ext4
        start: 129MiB
        end: 100%
        parttype: "b921b045-1df0-41c3-af44-4c6f280d3fae"
    mountpoints:
      - mountpoint: /
        partition: root
        options: [ x-systemd.growfs ]
      - mountpoint: /boot
        partition: boot

  - action: filesystem-deploy
    description: Step 98, Deploy the filesystem to partitions

  - action: recipe
    description: Step 99, Install the kernel
    recipe: steps/99-kernel/step.yaml

# ! TODO: Remove when replaced by a step
#  - action: install-deb
#    packages:
#      - kernel.deb
